### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by mooreann** [songlab-cal/rna-sieve#1]
Is there an alternate way to install or certain dependency packages it relies on that I may not have? Heres the installation error I'm getting:

(base) [mooreank@lngnode2 ~]$ pip3 install rna-sieve
ERROR: Could not find a version that satisfies the requirement rna-sieve (from versions: none)
ERROR: No matching distribution found for rna-sieve
(base) [mooreank@lngnode2 ~]$ pip install rna-sieve
ERROR: Could not find a version that satisfies the requirement rna-sieve (from versions: none)
ERROR: No matching distribution found for rna-sieve

**Comment by mooreann** [comment]
Also how should data be formatted? Genes x samples? Are you going to put your example data up soon?

**Comment by justjhong** [comment]
Apologies, that was a typo, you can install the package at `rnasieve` not `rna-sieve`. The example data will not be uploaded to this repository, but the .h5ad can be found freely from the Tabula Muris Senis AWS bucket here: https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/. The example notebook uses files from there without modification.

**Comment by numpde** [comment]
> Also how should data be formatted? Genes x samples? Are you going to put your example data up soon?

From cell [5] in [the notebook](https://github.com/songlab-cal/rna-sieve/blob/0197b3e/examples/example.ipynb) it appear that it *is* "genes x samples".
