### ISSUE TITLE
According to the example Jupyter notebook for Python 3 usage on github, but an error is reported

### ISSUE THREAD

**Issue by xiaoquexingchen** [songlab-cal/rna-sieve#3]
Hello:
I followed the example Jupyter notebook for Python 3 usage on GitHub, but I kept reporting the error "ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)", is this a data problem? But I just downloaded the dataset according to the code on github. I don't know what the problem is? Hope to get your answer, look forward to your reply, thank you very much!

Best wishes !

**Comment by justjhong** [comment]
Hi @xiaoquexingchen, thanks for bringing this up, I believe this bug popped up when I introduced the data download script. The example data we used changed format slightly from before. I'll have this fixed in an upcoming update hopefully this week.

**Comment by justjhong** [comment]
@xiaoquexingchen Please give it another try on the latest commit of the repo. Let me know if you experience any issues.

**Comment by justjhong** [comment]
Closing due to staleness, other users have reported this fix working for them in the notebook.
