### ISSUE TITLE
example data access 

### ISSUE THREAD

**Issue by annezxu** [songlab-cal/rna-sieve#6]
Hi, I was attempting to run the example.ipynb, but the sample data for this code (included in google drive links) can't be accessed. Is there any chance to change the sharing permissions for these files? Thank you!

**Comment by justjhong** [comment]
Hi @annezxu, I checked and unfortunately it looks like I cleared the files at some point because of storage limitations. The good news is that it should be fairly easy to recreate the files via the example_data.ipynb notebook which was used to create it.
