### ISSUE TITLE
access to the example data

### ISSUE THREAD

**Issue by hmkim93** [songlab-cal/rna-sieve#7]
Hi. I was trying to run example_data.ipynb, as the google drive link to the sample data in example.ipynb was not accessible, as mentioned in #6 

In the following codes:
if not path.exists(LOCAL_BULK_PATH):
    s3.Bucket(BUCKET_NAME).download_file(BULK_OBJECT_KEY, LOCAL_BULK_PATH)

if not path.exists(LOCAL_FACS_PATH):
    s3.Bucket(BUCKET_NAME).download_file(FACS_OBJECT_KEY, LOCAL_FACS_PATH)

The code returned "NoCredentialsError: Unable to locate credentials"
(that applies to both bulk and facs data)

Thanks in advance

**Comment by justjhong** [comment]
Hello, thanks for your interest in RNASieve! The Tabula Muris Senis data on AWS should be open to anyone as long as you have an AWS account. The dataset link can be found here: https://tabula-muris-senis.sf.czbiohub.org/. You can use the command `aws configure` to set up credentials locally on your computer before trying to run the command in the notebook.

Hope this helps!
